### ISSUE TITLE
configure: error: Could not compile with OMPL TypedSpaceInformation

### ISSUE THREAD

**Issue by tomsilver** [golems/amino#28]
I am working on installing amino (on my way to installing tmkit) on macOS Mojave following [the guide](http://amino.golems.org/installation.html).

I'm encountering the following when I run `./configure`:

```
...
checking for ompl... yes
checking bundled TypedSpaceInformation.h... no
checking compat TypedSpaceInformation.h using boost::shared_ptr... no
checking compat TypedSpaceInformation.h using std::shared_ptr... no
configure: error: Could not compile with OMPL TypedSpaceInformation
```

I can share the rest of the log if it's useful.

The first suspicious message is `checking bundled TypedSpaceInformation.h... no`, which suggests that it's looking for but not able to find that header file in the amino directory. But I see that in `amino/include/amino/ompl-compat/ompl/base`, the file `TypedSpaceInformation.h` does exist.

Thanks for any guidance you can offer!

**Comment by ndantam** [comment]
We have  previously run Amino on MacOS X.  However, I do not currently have access to Apple hardware, so it has been some time since I have been able to update the support. Still, let me see if I can help;

These configure tests are attempting to build against different versions of OMPL with incompatible changes (versions before `TypedSpaceInformation.h` was added, versions before/after the switch from `boost::shared_ptr` to `std::shared_ptr`).  If you are using a recent OMPL version, it should both include `TypedSpaceInformation.h`  and use `std::shared_ptr`.

The details of the configuration test and the specific compiler error messages are recorded in the generated `config.log` file.  Could you please check (/attach) this file to identify what has gone wrong?

One likely possibility: a recent release of OMPL has a missing include directory for Eigen in the pkg-config file (See "OMPL Missign Eigen dependency" in the amino INSTALL).  If this is the error indicated by `config.log`, you can fix by ensuring that Eigen is installed and updating the OMPL pkg-config file with the following line:

     Cflags: -I${includedir} -I/usr/include/eigen3

**Comment by tomsilver** [comment]
Thanks very much for the quick and helpful reply! I looked at config.log and indeed the missing Eigen dependency was the issue. I am now able to run `./configure` successfully.

In case others find this issue, I'll also mention that on macOS using brew, my OMPL pkg-config file was located at `/usr/local/Cellar/ompl/1.4.2/lib/pkgconfig/ompl.pc`, and I added the following line (slightly different from above):
```
Cflags: -I${includedir} -I/usr/local/include/eigen3
```
Thanks again for your help @ndantam!
