### ISSUE TITLE
ld: library not found for -lnlopt

### ISSUE THREAD

**Issue by tomsilver** [golems/amino#29]
(Hi, sorry to bother you again with what is probably a question with an obvious answer.)

I'm on macOS Mojave and I can successfully run `./configure`. When I subsequently run `make`, however, I encounter the following:

```
...
Warning: 'test_unit' defined but not used [-Wunused-function]
src/test/la_test.F90:219:0:

  219 |   subroutine test_colfit()
      | 
Warning: 'test_colfit' defined but not used [-Wunused-function]
  FCLD     la_test
ld: library not found for -lnlopt
collect2: error: ld returned 1 exit status
make[2]: *** [la_test] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

I do have `nlopt` installed. Some things I have tried, with no change, are:
- Add `PKG_CONFIG_PATH=/usr/local/opt/nlopt/lib/pkgconfig` during `./configure`
- Add `LIBS=-lnlopt` during `./configure`
- Add `LDFLAGS=-L/usr/local/opt/nlopt/lib` during `./configure`

Thanks for your help and patience!

**Comment by ndantam** [comment]
The configure script tries to link against nlopt, so presumably the library was found at that time.  You can check config.log for the test to find symbol `nlopt_create`.

It looks like linking a fortran test program is failing?  I wonder if the fortran linker is somehow missing the `-lnlopt` or a library path.  Getting the full command line with `make V=1` would show what specific flags are being passed to the fortran compiler and linker.  On my (Debian) workstation this shows the following (with a `-lnlopt` near the end):

    make V=1 la_test
    /bin/bash ./libtool  --tag=FC   --mode=link gfortran  -Wintrinsic-shadow -Wunused-parameter -Wtabs -Warray-temporaries -Wunderflow -Wimplicit-procedure -Wimplicit-interface -Wshadow -Wextra -pedantic -Wall -ffree-line-length-none -fimplicit-none -g -O2   -o la_test src/test/la_test.o libamino.la libtestutil.la -lnlopt -lglpk -lpthread -ldl -lm -llapack -lblas 
    libtool: link: gfortran -Wintrinsic-shadow -Wunused-parameter -Wtabs -Warray-temporaries -Wunderflow -Wimplicit-procedure -Wimplicit-interface -Wshadow -Wextra -pedantic -Wall -ffree-line-length-none -fimplicit-none -g -O2 -o .libs/la_test src/test/la_test.o  ./.libs/libamino.so ./.libs/libtestutil.a -lnlopt -lglpk -lpthread -ldl -lm -llapack -lblas

Is it possible that your fortran linker is using a different set of LDFLAGS from the C/C++ linker?  On my workstation, the relevant line from the Makefile shows the fortran linker uses the same LDFLAGS as the C/C++ Linker:

    FCLINK = $(LIBTOOL) $(AM_V_lt) --tag=FC $(AM_LIBTOOLFLAGS) \
	    $(LIBTOOLFLAGS) --mode=link $(FCLD) $(AM_FCFLAGS) $(FCFLAGS) \
	    $(AM_LDFLAGS) $(LDFLAGS) -o $@

A possible alternate approach: I am currently (for whatever reason) searching for `nlopt.h` and libnlopt in the configure script rather than using pkg-config.  If checking for nlopt via pkg-config would be easier to build on your system, that seems like an appropriate change.

**Comment by tomsilver** [comment]
Thank you again for the prompt and helpful reply!

I started looking into your suggestions and then eventually came back to the `LDFLAGS` env variable. It turns out that including `LDFLAGS=-L/usr/local/opt/nlopt/lib` with `./configure` does solve the problem after all. Sorry, I'm not sure how I missed that the first time.

Another small problem cropped up afterwards:

```
error: could not create '/python': Permission denied
make[2]: *** [all-python] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

but this was easily resolved with `sudo make` instead of make.

Thanks again for your help! I've now been able to complete the amino installation.
